jobs:
  build_deploy:
    machine: 
      image: ubuntu-2004:202010-01

    steps:
      - checkout
      - run:
          name: Install Packages
          command: npm install
      - run:
          name: Build Project
          command: npm run build

workflows:
  version: 2
  execute_bulk:
    jobs:
      - build_deploy